import express from 'express';
import http from 'http';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import { WebSocketServer, WebSocket } from 'ws';
import { GoogleGenAI, LiveServerMessage, Modality } from '@google/genai';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const server = http.createServer(app);
const port = parseInt(process.env.PORT || '3000', 10);

app.use(express.json({ limit: '60mb' }));
app.use(express.urlencoded({ extended: true, limit: '60mb' }));

// Server-side Google GenAI initialization with User-Agent header
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    },
  },
});

// 1. Multi-turn Chat, Search & Maps Grounding
app.post('/api/gemini/chat', async (req, res) => {
  try {
    const { messages, model, tool, systemInstruction } = req.body;
    const selectedModel = model || 'gemini-3.5-flash';

    // Format contents for multi-turn history
    const contents = (messages || []).map((m: any) => ({
      role: m.role === 'model' ? 'model' : 'user',
      parts: [{ text: m.content || m.text || '' }],
    }));

    // Configure tools if requested
    const tools: any[] = [];
    if (tool === 'googleSearch') {
      tools.push({ googleSearch: {} });
    } else if (tool === 'googleMaps') {
      tools.push({ googleMaps: {} });
    }

    const config: any = {};
    if (systemInstruction) {
      config.systemInstruction = systemInstruction;
    }
    if (tools.length > 0) {
      config.tools = tools;
    }

    const response = await ai.models.generateContent({
      model: selectedModel,
      contents,
      config: Object.keys(config).length > 0 ? config : undefined,
    });

    const candidate = response.candidates?.[0];
    const groundingMetadata = candidate?.groundingMetadata;

    res.json({
      text: response.text || '',
      groundingChunks: groundingMetadata?.groundingChunks || [],
      webSearchQueries: groundingMetadata?.webSearchQueries || [],
    });
  } catch (error: any) {
    console.error('Chat API Error:', error);
    res.status(500).json({ error: error.message || 'Error generating chat content' });
  }
});

// 2. Lyria Music Generation (Clip & Pro)
app.post('/api/gemini/music', async (req, res) => {
  try {
    const { prompt, model, imageBase64, mimeType } = req.body;
    const selectedModel = model === 'lyria-3-pro-preview' ? 'lyria-3-pro-preview' : 'lyria-3-clip-preview';

    let contents: any = prompt;
    if (imageBase64) {
      contents = {
        parts: [
          { text: prompt || 'Generate musical accompaniment for this visual scene.' },
          { inlineData: { data: imageBase64, mimeType: mimeType || 'image/jpeg' } },
        ],
      };
    }

    const responseStream = await ai.models.generateContentStream({
      model: selectedModel,
      contents,
    });

    let audioBase64 = '';
    let lyrics = '';
    let audioMimeType = 'audio/wav';

    for await (const chunk of responseStream) {
      const parts = chunk.candidates?.[0]?.content?.parts;
      if (!parts) continue;
      for (const part of parts) {
        if (part.inlineData?.data) {
          if (!audioBase64 && part.inlineData.mimeType) {
            audioMimeType = part.inlineData.mimeType;
          }
          audioBase64 += part.inlineData.data;
        }
        if (part.text && !lyrics) {
          lyrics = part.text;
        }
      }
    }

    if (!audioBase64) {
      return res.status(500).json({ error: 'No audio generated by Lyria model' });
    }

    res.json({
      audioBase64,
      mimeType: audioMimeType,
      lyrics,
    });
  } catch (error: any) {
    console.error('Music Generation Error:', error);
    res.status(500).json({ error: error.message || 'Error generating music with Lyria' });
  }
});

// 3. Image Generation and Editing (gemini-3.1-flash-image)
app.post('/api/gemini/image', async (req, res) => {
  try {
    const { prompt, imageBase64, mimeType, aspectRatio } = req.body;

    if (imageBase64) {
      // Edit image
      const response = await ai.models.generateContent({
        model: 'gemini-3.1-flash-image',
        contents: {
          parts: [
            {
              inlineData: {
                data: imageBase64,
                mimeType: mimeType || 'image/png',
              },
            },
            {
              text: prompt || 'Enhance and stylize this image in cyberpunk 2099 high-density HUD aesthetic.',
            },
          ],
        },
      });

      let outputImageBase64 = '';
      let outputMimeType = 'image/png';
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData && part.inlineData.data) {
          outputImageBase64 = part.inlineData.data;
          outputMimeType = part.inlineData.mimeType || 'image/png';
          break;
        }
      }

      if (!outputImageBase64) {
        return res.status(500).json({ error: 'No edited image returned' });
      }

      return res.json({ imageBase64: outputImageBase64, mimeType: outputMimeType });
    } else {
      // Generate image from text prompt
      const response = await ai.models.generateContent({
        model: 'gemini-3.1-flash-image',
        contents: {
          parts: [{ text: prompt }],
        },
        config: {
          imageConfig: {
            aspectRatio: aspectRatio || '1:1',
            imageSize: '1K',
          },
        },
      });

      let outputImageBase64 = '';
      let outputMimeType = 'image/png';
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData && part.inlineData.data) {
          outputImageBase64 = part.inlineData.data;
          outputMimeType = part.inlineData.mimeType || 'image/png';
          break;
        }
      }

      if (!outputImageBase64) {
        return res.status(500).json({ error: 'No image generated' });
      }

      return res.json({ imageBase64: outputImageBase64, mimeType: outputMimeType });
    }
  } catch (error: any) {
    console.error('Image Generation Error:', error);
    res.status(500).json({ error: error.message || 'Error processing image generation' });
  }
});

// 4. Veo Video Generation (Text-to-Video & Image-to-Video)
app.post('/api/gemini/video/generate', async (req, res) => {
  try {
    const { prompt, imageBase64, mimeType, aspectRatio } = req.body;

    const config: any = {
      numberOfVideos: 1,
      resolution: '720p',
      aspectRatio: aspectRatio === '9:16' ? '9:16' : '16:9',
    };

    let operation;
    if (imageBase64) {
      operation = await ai.models.generateVideos({
        model: 'veo-3.1-fast-generate-preview',
        prompt: prompt || 'A cinematic environmental atmospheric scan of this region',
        image: {
          imageBytes: imageBase64,
          mimeType: mimeType || 'image/png',
        },
        config,
      });
    } else {
      operation = await ai.models.generateVideos({
        model: 'veo-3.1-fast-generate-preview',
        prompt: prompt || 'Cybernetic solar storm sweeping across Gatesville Texas infrastructure',
        config,
      });
    }

    res.json({ operationName: operation.name });
  } catch (error: any) {
    console.error('Veo Generation Error:', error);
    res.status(500).json({ error: error.message || 'Error starting video generation' });
  }
});

app.post('/api/gemini/video/status', async (req, res) => {
  try {
    const { operationName } = req.body;
    if (!operationName) {
      return res.status(400).json({ error: 'Missing operationName' });
    }

    const op: any = { name: operationName };
    const updated = await ai.operations.getVideosOperation({ operation: op });
    res.json({ done: updated.done, error: updated.error });
  } catch (error: any) {
    console.error('Veo Status Error:', error);
    res.status(500).json({ error: error.message || 'Error checking video status' });
  }
});

app.post('/api/gemini/video/download', async (req, res) => {
  try {
    const { operationName } = req.body;
    if (!operationName) {
      return res.status(400).json({ error: 'Missing operationName' });
    }

    const op: any = { name: operationName };
    const updated = await ai.operations.getVideosOperation({ operation: op });
    const uri = updated.response?.generatedVideos?.[0]?.video?.uri;

    if (!uri) {
      return res.status(404).json({ error: 'Video URI not ready or available' });
    }

    const videoRes = await fetch(uri, {
      headers: { 'x-goog-api-key': process.env.GEMINI_API_KEY || '' },
    });

    res.setHeader('Content-Type', 'video/mp4');
    const arrayBuffer = await videoRes.arrayBuffer();
    res.send(Buffer.from(arrayBuffer));
  } catch (error: any) {
    console.error('Veo Download Error:', error);
    res.status(500).json({ error: error.message || 'Error downloading generated video' });
  }
});

// 5. Audio Transcription (gemini-3.5-transcribe)
app.post('/api/gemini/transcribe', async (req, res) => {
  try {
    const { audioBase64, mimeType } = req.body;
    if (!audioBase64) {
      return res.status(400).json({ error: 'Missing audio data' });
    }

    const audioPart = {
      inlineData: {
        mimeType: mimeType || 'audio/webm',
        data: audioBase64,
      },
    };

    const response = await ai.models.generateContent({
      model: 'gemini-3.5-transcribe',
      contents: {
        parts: [audioPart, { text: 'Transcribe this spoken audio precisely.' }],
      },
    });

    res.json({ text: response.text || '' });
  } catch (error: any) {
    console.error('Transcription Error:', error);
    res.status(500).json({ error: error.message || 'Error transcribing audio' });
  }
});

// 6. Real-time Live API WebSocket Setup (gemini-3.8-live)
const wss = new WebSocketServer({ noServer: true });

server.on('upgrade', (request, socket, head) => {
  const { pathname } = new URL(request.url || '', `http://${request.headers.host}`);
  if (pathname === '/api/gemini/live') {
    wss.handleUpgrade(request, socket, head, (ws) => {
      wss.emit('connection', ws, request);
    });
  }
});

wss.on('connection', async (clientWs: WebSocket) => {
  console.log('🎙️ [LIVE API] Operator connected to Gemini Live voice stream');
  try {
    const session = await ai.live.connect({
      model: 'gemini-3.8-live',
      config: {
        responseModalities: [Modality.AUDIO],
        speechConfig: {
          voiceConfig: { prebuiltVoiceConfig: { voiceName: 'Zephyr' } },
        },
        systemInstruction:
          'You are the 2099 Grid Guardian AI Operator Co-Pilot. You assist the operator with space weather defense, 12D scalar tonal protection, biometric coherence analysis, and infrastructure shielding. Speak concisely and calmly.',
      },
      callbacks: {
        onmessage: (message: LiveServerMessage) => {
          const audio = message.serverContent?.modelTurn?.parts?.[0]?.inlineData?.data;
          if (audio && clientWs.readyState === WebSocket.OPEN) {
            clientWs.send(JSON.stringify({ audio }));
          }
          if (message.serverContent?.interrupted && clientWs.readyState === WebSocket.OPEN) {
            clientWs.send(JSON.stringify({ interrupted: true }));
          }
        },
      },
    });

    clientWs.on('message', (data) => {
      try {
        const parsed = JSON.parse(data.toString());
        if (parsed.audio) {
          session.sendRealtimeInput({
            audio: { data: parsed.audio, mimeType: 'audio/pcm;rate=16000' },
          });
        }
      } catch (err) {
        console.error('Error parsing client live message:', err);
      }
    });

    clientWs.on('close', () => {
      console.log('🎙️ [LIVE API] Operator disconnected');
    });
  } catch (err) {
    console.error('Live connect error:', err);
    if (clientWs.readyState === WebSocket.OPEN) {
      clientWs.send(JSON.stringify({ error: 'Live API connection error' }));
    }
  }
});

// Vite Middleware for Development / Static serving for Production
async function startServer() {
  if (process.env.NODE_ENV === 'production') {
    app.use(express.static(path.resolve(__dirname, 'dist')));
    app.get('*', (_req, res) => {
      res.sendFile(path.resolve(__dirname, 'dist', 'index.html'));
    });
  } else {
    const { createServer: createViteServer } = await import('vite');
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  }

  server.listen(port, '0.0.0.0', () => {
    console.log(`🚀 [SERVER] Grid Guardian V2099 full-stack server running on port ${port}`);
  });
}

startServer();
